### ISSUE TITLE
[TEST] 테스트 환경에서 ddl-auto : none으로 작성해서 전체 테스트 구동시, 에러 발생

### ISSUE THREAD

**Issue by heebong** [everyone-driven-development/miniprojects-2019#200]
* 현상 : test에서 ddl-auto:none 으로 변경 후,
schema.sql 과 data.sql을 함께 작성하고
모든 테스트를 구동하면 ApplicationContext가 구동되지 않는다는 에러가 발생함.

* WebTestClient를 사용하는 테스트만 따로 구동할 시 에러 발생하지 않음
* data.sql을 삭제하고 돌리면 에러가 발생하지 않음

**Comment by Laterality** [comment]
schema.sql의 앞부분에 `DROP TABLE IF EXISTS SOME_TABLE;` 형태로 테이블 삭제 구문을 추가하면 해결됩니다!
