### ISSUE TITLE
index.html의 헤더 이벤트 리스너 추가 이슈

### ISSUE THREAD

**Issue by Laterality** [everyone-driven-development/miniprojects-2019#51]
헤더를 템플릿으로 분리하면서 헤더가 추가되기 전에 이벤트 리스너를 추가하려고 해서 해당 엘리먼트를 찾지 못하는 이슈가 있습니다.

**Comment by kangmin46** [comment]
add header 메서드를 호출하는 부분을 script import할때 제일 위로 올리면 어떤가요?
