### ISSUE TITLE
머지 방식 구체화

### ISSUE THREAD

**Issue by Laterality** [everyone-driven-development/miniprojects-2019#53]
PR -> 리뷰 -> 머지의 절차를 팀 상황이나 일정에 맞춰서 구체적으로 고민해봐야 할 것 같아요. 
머지 커밋 메시지도 실질적인 변경 사항을 담을 수 있는 포맷으로 변경하는 것도 필요할 것 같습니다.

**Comment by Conatuseus** [comment]
본인 제외 2명이 approve하면 본인이 merge하기.
