### ISSUE TITLE
궁금한 이유 설명타임

### ISSUE THREAD

**Issue by heebong** [everyone-driven-development/miniprojects-2019#78]
에단쓰

**Comment by kimjungmin-developer** [comment]
설명이 필요한 이슈:
1. 배포환경에서 테스트코드는 어떻게 도는가?
2. local에서 mysql에서 h2로 왜 바꿧나?
3. application.yml과 application-production은 왜 나눴나?
4. mysql에서 잘돌았었는데 갑자기 안돌아간 이유는 뭔가(local 에서)
5. enginex 선택한 이유
6. docker를 선택한 이유

**Comment by Laterality** [comment]
1. build.gralde에 jupiter-engine 의존성 추가 후 test 태스크에 `useJUnitPlatform` 추가하면 빌드 과정에서 자동으로 테스트를 함께 수행합니다. (버전 정보를 넣지 마세요!!)
2. 개발환경에서 mysql 세팅이 번거롭다고 느꼈고, 프로덕션 세팅을 굳이 application.yml에 둘 필요가 없어져서 h2로 변경했습니다.
3. 개발 환경과 프로덕션 환경에서 사용하는 설정을 분리하기 위해 사용했습니다. 분리하기 위해 별도의 `.yml` 파일을 생성했고, `java -jar -Dspring.profiles.active=production $JAR_NAME
`과 같이 jar파일 실행시에 사용할 프로파일을 지정했습니다.
4. 구체적인 원인은 확실하지 않으나, JPA의 Dialect 설정과 App 컨테이너 실행 시 DB 컨테이너가 완전히 준비되도록 기다리게 변경하여 해결했습니다.
5. nginx입니다.  reverse proxy 기능을 사용하기 위해서입니다. reverse proxy 적용 시 로드밸런싱과 HTTPS 적용 편의성 등 장점이 있어 적용했습니다. 
6. 그냥.
