### ISSUE TITLE
로그인/ 회원가입 페이지 어떻게 보여줄거?

### ISSUE THREAD

**Issue by heebong** [everyone-driven-development/miniprojects-2019#79]
비 로그인일 경우 프로필 영역 클릭하면
로그인 페이지로 연결하고
거기서 회원가입으로 연결?

**Comment by Conatuseus** [comment]
비 로그인일 경우 프로필 영역 클릭하면
로그인 페이지로 연결하고
거기서 회원가입으로 연결
